export const PROFIL_REQUEST = 'PROFIL_REQUEST';
export const PROFIL_SUCCESS = 'PROFIL_SUCCESS';
export const PROFIL_FAILURE = 'PROFIL_FAILURE';

export const EDIT_PROFIL_REQUEST = 'EDIT_PROFIL_REQUEST';
export const EDIT_PROFIL_SUCCESS = 'EDIT_PROFIL_SUCCESS';
export const EDIT_PROFIL_FAILURE = 'EDIT_PROFIL_FAILURE';

export const OTHER_PROFIL_REQUEST = 'OTHER_PROFIL_REQUEST';
export const OTHER_PROFIL_SUCCESS = 'OTHER_PROFIL_SUCCESS';
export const OTHER_PROFIL_FAILURE = 'OTHER_PROFIL_FAILURE';
